function createFourier(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 14-Jul-2022 13:30:49

% Create figure
figure1 = figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'Color',[0 0 1]);

% Create ylabel
ylabel({'Size of Performance BottleNeck (in units)'});

% Create xlabel
xlabel({'Time (in sec.)'});

% Create title
title({'Time Domain'});

box(subplot1,'on');
hold(subplot1,'off');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X2,Y2,'Parent',subplot2,'Color',[1 0 0]);

% Create ylabel
ylabel({'Frenquency'});

% Create xlabel
xlabel({'Samples'});

% Create title
title({'Frenquency Doman'});

box(subplot2,'on');
hold(subplot2,'off');
